swagger: '2.0'
info:
  description: "Documentação da API do projeto de capacitação back-end, feito por Tiago Viegas Pires Lage."
  version: '1.0.0'
  title: 'Capacitação Back-end'
host: 'localhost:3000'
basePath: '/'
schemes:
  - 'http'
paths:
  #auth - relacionado ao usuario em sí, seja ele admin ou não
  /auth/register:
    post:
      tags:
        - 'auth'
      summary: 'registra usuário'
      description: ''
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados de cadastro do usuário'
          required: true
          schema:
            type: 'object'
            properties:
              name:
                type: 'string'
                example: 'teste'
              email:
                type: 'string'
                example: 'teste@gmail.com'
              password:
                type: 'string'
                example: '1234'
              isAdmin:
                type: 'boolean'
                example: true
      responses:
        '400':
          description: 'User already exists or Registration failed'
        '500':
          description: 'Registration failed'
  /auth/login:
    post:
      tags:
        - 'auth'
      summary: 'faz o login do usuário'
      description: 'login do usuário'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados de login do usuário'
          required: true
          schema:
            type: 'object'
            properties:
              email:
                type: 'string'
                example: 'teste@gmail.com'
              password:
                type: 'string'
                example: '1111'
      responses:
        '400':
          description: 'invalid password'
        '404':
          description: 'user not found'
        '500':
          description: 'internal server error'
  /auth/post/addImage/{userId}:
    post:
      tags:
        - 'auth'
      summary: 'Adiciona imagem de perfil'
      description: 'Adiciona uma imagem de perfil para um usuário específico'
      consumes:
        - 'multipart/form-data'
      parameters:
        - in: path
          name: userId
          required: true
          description: 'ID do usuário'
          schema:
            type: string
            example: '647cee9577842b1cbc4c0597'
        - in: formData
          name: profileImage
          description: 'Imagem de perfil do usuário'
          required: true
          type: file
      responses:
        '200':
          description: 'Sucesso'
        '400':
          description: 'Nenhuma imagem enviada'
        '404':
          description: 'Usuário não encontrado'
        '500':
          description: 'Ocorreu um erro, tente novamente'

  /auth/forgot-password:
    post:
      tags:
        - 'auth'
      summary: 'Esqueceu a senha'
      description: 'Envia um e-mail com instruções para redefinir a senha do usuário'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados necessários para redefinir a senha'
          required: true
          schema:
            type: 'object'
            properties:
              email:
                type: 'string'
                example: "teste@gmail.com"
      responses:
        '400':
          description: 'fail sending recover password mail'
        '404':
          description: 'user not found'
        '500':
          description: 'internal server error'
  /auth/reset-password:
    post:
      tags:
        - 'auth'
      summary: 'Redefinir senha'
      description: 'Redefine a senha do usuário com base no token de redefinição'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados necessários para redefinir a senha'
          required: true
          schema:
            type: 'object'
            properties:
              email:
                type: 'string'
                example: "teste@gmail.com"
              token:
                type: 'string'
                example: "3b9d58877c1020fa0469d1ca364c79dfd3cfc71f"
              newPassword:
                type: 'string'
                example: "1111"
      responses:
        '400':
          description: 'Invalid token'
        '404':
          description: 'User not found'
        '500':
          description: 'Internal server error'
  /auth/user/{userId}/profile-image:
    get:
      tags:
        - 'auth'
      summary: 'Obter imagem de perfil do usuário'
      description: 'Retorna a imagem de perfil do usuário com base no ID do usuário'
      produces:
        - 'image/png'
        - 'image/jpeg'
      parameters:
        - in: path
          name: userId
          description: 'ID do usuário'
          required: true
          schema:
            type: string
            example: "647cee9577842b1cbc4c0597"
      responses:
        '200':
          description: 'Imagem de perfil do usuário encontrada'
          content:
            'image/png':
              schema:
                type: string
                format: binary
            'image/jpeg':
              schema:
                type: string
                format: binary
        '404':
          description: 'Usuário ou imagem não encontrada'
        '500':
          description: 'Falha ao recuperar a imagem do usuário'

  # exemplo - relacionado aos dados que o usúario pode adicionar e alterar,
  # dependendo de seu tipo, se ele é admin ou nao
  /exemplo/get:
    get:
      tags:
        - 'exemplo'
      summary: 'Obter todos os projetos'
      description: 'Obter todos os projetos'
      operationId: 'getAllProjects'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'Projetos obtidos com sucesso'
          schema:
            type: 'array'
            items:
              type: 'object'
              properties:
                title:
                  type: 'string'
                category:
                  type: 'string'
                slug:
                  type: 'string'
                featuredImage:
                  type: 'string'
        '400':
          description: 'Não foi possível obter os dados do projeto. Tente novamente'


  /exemplo/get/{projectSlug}:
    get:
      tags:
        - 'exemplo'
      summary: 'Obter projeto específico'
      description: 'Retorna os dados de um projeto com base no slug'
      parameters:
        - in: 'path'
          name: 'projectSlug'
          description: 'Slug do projeto'
          required: true
          schema:
            type: 'string'
            example: 'ofkmgfgf'
      responses:
        '400':
          description: 'Nao foi possivel obter os dados do projeto. Tente novamente'


  /exemplo/post:
    post:
      tags:
        - 'exemplo'
      summary: 'post de dados'
      description: 'post de dados'
      operationId: 'signUp'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados para o post'
          required: true
          schema:
            type: 'object'
            properties:
              title:
                type: 'string'
                example: 'ofkmgfgf'
              description:
                type: 'string'
                example: 'rter'
              category:
                type: 'string'
                example: 'exehfhgfmplo'
        - in: 'header'
          name: 'Authorization'
          description: 'Token de autenticação do administrador'
          required: true
          schema:
            type: 'string'
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NDdjZWU5NTc3ODQyYjFjYmM0YzA1OTciLCJpYXQiOjE2ODU5MDk5MDksImV4cCI6MTY4NTk5NjMwOX0.OR_4HM6uyXQMZEBuarO51DQnfHkjYLc_XP_nnNHDZPA"
      responses:
        '400':
          description: 'Nao foi possivel salvar seu projeto. Verifique os dados e tente novamente'

  /exemplo/put/{projectId}:
    put:
      tags:
        - 'exemplo'
      summary: Atualizar um projeto
      description: Atualiza as informações de um projeto no banco de dados.
      parameters:
        - in: path
          name: projectId
          description: ID do projeto a ser atualizado
          required: true
          schema:
            type: string
            example: "647cf1ff77842b1cbc4c05a6"
        - in: 'header'
          name: 'Authorization'
          description: 'Token de autenticação do administrador'
          required: true
          schema:
            type: 'string'
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NDdjZWU5NTc3ODQyYjFjYmM0YzA1OTciLCJpYXQiOjE2ODU5MDk5MDksImV4cCI6MTY4NTk5NjMwOX0.OR_4HM6uyXQMZEBuarO51DQnfHkjYLc_XP_nnNHDZPA"
        - in: body
          name: body
          description: Objeto contendo as informações atualizadas do projeto
          required: true
          schema:
            type: object
            properties:
              title:
                type: string
                example: "teste"
              description:
                type: string
                example: "teste"
              category:
                type: string
                example: "teste"
      responses:
        '201': 
          description: 'Projeto atualizado com sucesso'
          schema:
            type: 'array'
            items:
              type: 'object'
              properties:
                title:
                  type: 'string'
                  example: 'teste'
                category:
                  type: 'string'
                  example: "teste"
                slug:
                  type: 'string'
                  example: "teste"
        '400':
          description: Erro ao atualizar o projeto


  /exemplo/delete/{projectId}:
    delete:
      tags:
        - 'exemplo'
      summary: Excluir um projeto
      description: Remove um projeto do banco de dados.
      parameters:
        - in: path
          name: projectId
          description: ID do projeto a ser excluído
          required: true
          schema:
            type: string
            example: "647cf1ff77842b1cbc4c05a6"
        - in: 'header'
          name: 'Authorization'
          description: 'Token de autenticação do administrador'
          required: true
          schema:
            type: 'string'
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NDdjZWU5NTc3ODQyYjFjYmM0YzA1OTciLCJpYXQiOjE2ODU5MDk5MDksImV4cCI6MTY4NTk5NjMwOX0.OR_4HM6uyXQMZEBuarO51DQnfHkjYLc_XP_nnNHDZPA"
      responses:
        '201':
          description: 'deleted!'
        '400':
          description: "erro ao remover projeto, tente novamente"
  /exemplo/post/featured-image/{projectId}:
    post:
      tags:
        - 'exemplo'
      summary: Associar imagem destacada a um projeto
      description: Associa uma imagem destacada a um projeto específico.
      parameters:
        - in: path
          name: projectId
          description: ID do projeto ao qual a imagem será associada
          required: true
          schema:
            type: string
            example: "647cf1ff77842b1cbc4c05a6"
        - in: 'header'
          name: 'Authorization'
          description: 'Token de autenticação do administrador'
          required: true
          schema:
            type: 'string'
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NDdjZWU5NTc3ODQyYjFjYmM0YzA1OTciLCJpYXQiOjE2ODU5MDk5MDksImV4cCI6MTY4NTk5NjMwOX0.OR_4HM6uyXQMZEBuarO51DQnfHkjYLc_XP_nnNHDZPA"
        - in: formData
          name: featured-image
          description: Imagem destacada a ser associada
          required: true
          type: file
      responses:
        '400':
          description: "Nenhuma imagem enviada"
        '500':
          description: "Ocorreu um erro, tente novamente"
  /exemplo/post/featured-images/{projectId}:
    post:
      tags:
        - 'exemplo'
      summary: 'Associar imagem(s) destacada(s) a um projeto'
      description: 'Associa uma ou mais imagens destacadas a um projeto específico'
      consumes:
        - multipart/form-data
      parameters:
        - in: path
          name: projectId
          description: 'ID do projeto ao qual as imagens serão associadas'
          required: true
          schema:
            type: string
            example: '647cf1ff77842b1cbc4c05a6'
        - in: 'header'
          name: 'Authorization'
          description: 'Token de autenticação do administrador'
          required: true
          schema:
            type: 'string'
            example: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NDdjZWU5NTc3ODQyYjFjYmM0YzA1OTciLCJpYXQiOjE2ODYxMDg3NzIsImV4cCI6MTY4NjE5NTE3Mn0.BVNMrdH7mKzjH-myUF82g4x5TAHxAuAhDiKUAEfEaSk'
        - in: formData
          name: images
          description: 'Imagens destacadas do projeto'
          required: true
          type: object
          properties:
            images:
              type: array
              items:
                type: file
                format: binary
      responses:
        '400':
          description: 'Nenhuma imagem enviada'
        '500':
          description: 'Ocorreu um erro, tente novamente'

definitions:
  admin:
    type: 'object'
    properties:
      id:
        type: 'string'
        example: '6473d2246ff912156c10a096'
      name:
        type: 'string'
        example: 'tiago'
      email:
        type: 'string'
        example: 'tiago@gmail.com'
      passwoed:
        type: 'string'
        example: '1234'
      profileImage: 
        type: string
        required: false
      isAdmin:
        type: 'boolean'
        example: true
  user:
    type: 'object'
    properties:
      id:
        type: 'string'
        example: '6473d2246ff912156c10a096'
      name:
        type: 'string'
        example: 'tiago'
      email:
        type: 'string'
        example: 'tiago@gmail.com'
      passwoed:
        type: 'string'
        example: '1234'
      isAdmin:
        type: 'boolean'
        example: false
      profileImage: 
        type: string
        required: false
  dados:
    type: 'object'
    properties:
      title:
        type: 'string'
        example: 'teste'
      description:
        type: 'string'
        example: 'teste'
      slug:
        type: 'string'
        example: 'teste'
  dadosComImagem:
    type: 'object'
    properties:
      title:
        type: 'string'
        example: 'teste'
      description:
        type: 'string'
        example: 'teste'
      slug:
        type: 'string'
        example: 'teste'
      featuredImage:
        type: 'string'
        example: 'uploads/images/teste.jpeg'

