swagger: '2.0'
info:
  description: "Documentação da API do projeto de capacitação back-end, feito por Tiago Viegas Pires Lage."
  version: '1.0.0'
  title: 'Capacitação Back-end'
host: 'localhost:3000'
basePath: '/'
schemes:
  - 'https'
paths:
  #auth - relacionado ao usuario em sí, seja ele admin ou não
  /auth/register:
    post:
      tags:
        - 'auth'
      summary: 'registra usuário'
      description: ''
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados de cadastro do usuário'
          required: true
          schema:
            type: 'object'
            properties:
              name:
                type: 'string'
                example: 'tiago'
              email:
                type: 'string'
                example: 'tiago@gmail.com'
              password:
                type: 'string'
                example: '1234'
              isAdmin:
                type: 'boolean'
                example: true
      responses:
        '400':
          description: 'User already exists or Registration failed'
        '500':
          description: 'Registration failed'
  /auth/login:
    post:
      tags:
        - 'auth'
      summary: 'faz o login do usuário'
      description: 'login do usuário'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados de login do usuário'
          required: true
          schema:
            type: 'object'
            properties:
              email:
                type: 'string'
                example: 'tiago@gmail.com'
              password:
                type: 'string'
                example: '1234'
      responses:
        '400':
          description: 'invalid password'
        '404':
          description: 'user not found'
        '500':
          description: 'internal server error'
  /post/addImage/{userId}:
    post:
      tags:
        - 'auth'
      summary: 'Adiciona imagem de perfil'
      description: 'Adiciona uma imagem de perfil para um usuário específico'
      consumes:
        - 'multipart/form-data'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: 'userId'
          description: 'ID do usuário'
          required: true
          type: 'string'
        - in: 'formData'
          name: 'profileImage'
          description: 'Imagem de perfil do usuário'
          required: true
          type: 'file'
      responses:
        '400':
          description: 'Nenhuma imagem enviada'
        '404':
          description: 'Usuário não encontrado'
        '500':
          description: 'Ocorreu um erro, tente novamente'
  /forgot-password:
    post:
      tags:
        - 'auth'
      summary: 'Esqueceu a senha'
      description: 'Envia um e-mail com instruções para redefinir a senha do usuário'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados necessários para redefinir a senha'
          required: true
          schema:
            type: 'object'
            properties:
              email:
                type: 'string'
                example: "tiago@gmail.com"
      responses:
        '400':
          description: 'fail sending recover password mail'
        '404':
          description: 'user not found'
        '500':
          description: 'internal server error'
  /reset-password:
    post:
      tags:
        - 'auth'
      summary: 'Redefinir senha'
      description: 'Redefine a senha do usuário com base no token de redefinição'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados necessários para redefinir a senha'
          required: true
          schema:
            type: 'object'
            properties:
              email:
                type: 'string'
                example: "tiago@gmail.com"
              token:
                type: 'string'
                example: "0a7b02a0b024ad1ea0bfbf4599004840d0dd97ff"
              newPassword:
                type: 'string'
                example: "1111"
      responses:
        '400':
          description: 'Invalid token'
        '404':
          description: 'User not found'
        '500':
          description: 'Internal server error'
  /user/{userId}/profile-image:
    get:
      tags:
        - 'auth'
      summary: 'Obter imagem de perfil do usuário'
      description: 'Retorna a imagem de perfil do usuário com base no ID do usuário'
      produces:
        - 'profile-image/*'
      parameters:
        - in: 'body'
          name: 'userId'
          description: 'ID do usuário'
          required: true
          schema:
            type: 'string'
            example: "6473b988a7ce3c0e24913d67"
      responses:
        '404':
          description: 'User or image not found'
        '500':
          description: 'Failed to retrieve user image'
  # exemplo - relacionado aos dados que o usúario pode adicionar e alterar,
  # dependendo de seu tipo, se ele é admin ou nao
  /exemplo/get:
    get:
      tags:
        - 'exemplo'
      summary: 'Obter todos os projetos'
      description: 'Obter todos os projetos'
      operationId: 'getAllProjects'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'Projetos obtidos com sucesso'
          schema:
            type: 'array'
            items:
              type: 'object'
              properties:
                title:
                  type: 'string'
                category:
                  type: 'string'
                slug:
                  type: 'string'
                featuredImage:
                  type: 'string'
        '400':
          description: 'Não foi possível obter os dados do projeto. Tente novamente'


  /exemplo/get/{projectSlug}:
    get:
      tags:
        - 'exemplo'
      summary: 'Obter projeto específico'
      description: 'Retorna os dados de um projeto com base no slug'
      parameters:
        - in: 'body'
          name: 'projectSlug'
          description: 'Slug do projeto'
          required: true
          schema:
            type: "string"
            example: "teste"
      responses:
        '400':
          description: 'Nao foi possivel obter os dados do projeto. Tente novamente'

  /exemplo/post:
   post:
    tags:
      - 'exemplo'
    summary: 'post de dados'
    description: 'post de dados'
    operationId: 'signUp'
    consumes:
      - 'application/json'
    produces:
      - 'application/json'
    parameters:
      - in: 'body'
        name: 'body'
        description: 'Dados para o post'
        required: true
        schema:
              type: 'object'
              properties:
                title:
                  type: 'string'
                  example: 'exemplo'
                description:
                  type: 'string'
                  example: 'exemplo'
                category:
                  type: 'string'
                  example: 'exemplo'
      - in: body
        name: Authorization
        description: Token de autenticação do administrador
        required: true
        schema:
            type: string
            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NDczYjljZmE3Y2UzYzBlMjQ5MTNkNmEiLCJpYXQiOjE2ODUzMTE5MjIsImV4cCI6MTY4NTM5ODMyMn0.AB9I9_EG1Yje4MdHWvZvmim5uV1fe5dFJSBEExA8J-A"
    responses:
       '400':
         description: 'Nao foi possivel salvar seu projeto. Verifique os dados e tente novamente'
  /exemplo/put/{projectId}:
    put:
      tags:
        - 'exemplo'
      summary: Atualizar um projeto
      description: Atualiza as informações de um projeto no banco de dados.
      parameters:
        - in: body
          name: projectId
          description: ID do projeto a ser atualizado
          required: true
          schema:
            type: string
            example: "6473d2246ff912156c10a096"
        - in: body
          name: Authorization
          description: Token de autenticação do administrador
          required: true
          schema:
            type: string
            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NDczYjljZmE3Y2UzYzBlMjQ5MTNkNmEiLCJpYXQiOjE2ODUzMTE5MjIsImV4cCI6MTY4NTM5ODMyMn0.AB9I9_EG1Yje4MdHWvZvmim5uV1fe5dFJSBEExA8J-A"
        - in: body
          name: body
          description: Objeto contendo as informações atualizadas do projeto
          required: true
          schema:
            type: object
            properties:
              title:
                type: string
                example: "teste"
              description:
                type: string
                example: "teste"
              category:
                type: string
                example: "teste"
      responses:
        '201': 
          description: 'Projeto atualizado com sucesso'
          schema:
            type: 'array'
            items:
              type: 'object'
              properties:
                title:
                  type: 'string'
                  example: 'teste'
                category:
                  type: 'string'
                  example: "teste"
                slug:
                  type: 'string'
                  example: "teste"
        '400':
          description: Erro ao atualizar o projeto


  /delete/{projectId}:
    delete:
      tags:
        - 'exemplo'
      summary: Excluir um projeto
      description: Remove um projeto do banco de dados.
      parameters:
        - in: body
          name: projectId
          description: ID do projeto a ser excluído
          required: true
          schema:
            type: string
            example: "6473d2246ff912156c10a096"
        - in: body
          name: Authorization
          description: Token de autenticação do administrador
          required: true
          schema:
            type: string
            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NDczYjljZmE3Y2UzYzBlMjQ5MTNkNmEiLCJpYXQiOjE2ODUzMTE5MjIsImV4cCI6MTY4NTM5ODMyMn0.AB9I9_EG1Yje4MdHWvZvmim5uV1fe5dFJSBEExA8J-A"
      responses:
        '201':
          description: 'deleted!'
        '400':
          description: "erro ao remover projeto, tente novamente"
  /post/featured-image/{projectId}:
    post:
      tags:
        - 'exemplo'
      summary: Associar imagem destacada a um projeto
      description: Associa uma imagem destacada a um projeto específico.
      parameters:
        - in: body
          name: projectId
          description: ID do projeto ao qual a imagem será associada
          required: true
          schema:
            type: string
            example: "6473d2246ff912156c10a096"
        - in: body
          name: Authorization
          description: Token de autenticação do administrador
          required: true
          schema:
            type: string
            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NDczYjljZmE3Y2UzYzBlMjQ5MTNkNmEiLCJpYXQiOjE2ODUzMTE5MjIsImV4cCI6MTY4NTM5ODMyMn0.AB9I9_EG1Yje4MdHWvZvmim5uV1fe5dFJSBEExA8J-A"
        - in: formData
          name: featured-image
          description: Imagem destacada a ser associada
          required: true
          type: file
      responses:
        '400':
          description: "Nenhuma imagem enviada"
        '500':
          description: "Ocorreu um erro, tente novamente"


  /post/featured-images/{projectId}:
    post:
      tags:
        - 'exemplo'
      summary: Associar imagem(s) destacada(s) a um projeto
      description: Associa uma ou mais imagens destacadas a um projeto específico.
      parameters:
        - in: body
          name: projectId
          description: ID do projeto ao qual as imagens serão associadas
          required: true
          schema:
            type: string
            example: "6473d2246ff912156c10a096"
        - in: body
          name: Authorization
          description: Token de autenticação do administrador
          required: true
          schema:
            type: string
            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NDczYjljZmE3Y2UzYzBlMjQ5MTNkNmEiLCJpYXQiOjE2ODUzMTE5MjIsImV4cCI6MTY4NTM5ODMyMn0.AB9I9_EG1Yje4MdHWvZvmim5uV1fe5dFJSBEExA8J-A"
        - in: formData
          name: featured-images
          description: Arquivos de imagem a serem associados
          required: true
          type: array
          items:
            type: string
            format: binary

        #requestBody:
        #  required: true
        #  content:
        #    multipart/form-data:
        #      schema:
         #       type: object
         #       properties:
         #         images:
         #           type: array
         #           items:
          #            type: string
        #             format: binary*/
      responses:
        '400':
          description: "Nenhuma imagem enviada"
        '500':
          description: "Ocorreu um erro, tente novamente"


definitions:
  admin:
    type: 'object'
    properties:
      id:
        type: 'string'
        example: '6473d2246ff912156c10a096'
      name:
        type: 'string'
        example: 'tiago'
      email:
        type: 'string'
        example: 'tiago@gmail.com'
      passwoed:
        type: 'string'
        example: '1234'
      isAdmin:
        type: 'boolean'
        example: true
  user:
    type: 'object'
    properties:
      id:
        type: 'string'
        example: '6473d2246ff912156c10a096'
      name:
        type: 'string'
        example: 'tiago'
      email:
        type: 'string'
        example: 'tiago@gmail.com'
      passwoed:
        type: 'string'
        example: '1234'
      isAdmin:
        type: 'boolean'
        example: false
  dados:
    type: 'object'
    properties:
      title:
        type: 'string'
        example: 'teste'
      description:
        type: 'string'
        example: 'teste'
      slug:
        type: 'string'
        example: 'teste'
  dadosComImagem:
    type: 'object'
    properties:
      title:
        type: 'string'
        example: 'teste'
      description:
        type: 'string'
        example: 'teste'
      slug:
        type: 'string'
        example: 'teste'
      featuredImage:
        type: 'string'
        example: 'uploads/images/teste.jpeg'

